name: Build

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    
    - name: get pods home directory from cache
      uses: actions/cache@v1
      with:
        path: ./iGlance/Pods
        key: ${{ runner.os }}--pods-home-key-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}--pods-home-key-
          
    - name: get installed pods from cache
      uses: actions/cache@v1
      with:
        path: ./iGlance/Pods
        key: ${{ runner.os }}--pods-key-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}--pods-key-
          
    - name: execute 'pod install' 
      working-directory: ./iGlance
      run: pod install
      env:
        CP_HOME_DIR: ./cocoaPodsHomeDir  

    - name: build project
      working-directory: ./iGlance
      run: xcodebuild -workspace iGlance.xcworkspace -scheme iGlance -config Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
